
#Evolved Mekanism Tools Config. This config is synced from server to client.
[tools]

	[tools.mobArmorSpawnRate]

		#Spawn chances for pieces of better_gold gear. Note: These values are after the general mobArmorSpawnRate (or corresponding weapon rate) has been checked, and after an even split between material types has been done.
		[tools.mobArmorSpawnRate.better_gold]
			#Whether mobs can spawn with better_gold Weapons.
			canSpawnWeapon = true
			#The chance that mobs will spawn with better_gold Swords rather than better_gold Shovels.
			#Range: 0.0 ~ 1.0
			swordWeight = 0.33
			#The chance that mobs can spawn with better_gold Helmets.
			#Range: 0.0 ~ 1.0
			helmetChance = 1.0
			#The chance that mobs can spawn with better_gold Chestplates.
			#Range: 0.0 ~ 1.0
			chestplateChance = 1.0
			#The chance that mobs can spawn with better_gold Leggings.
			#Range: 0.0 ~ 1.0
			leggingsChance = 1.0
			#The chance that mobs can spawn with better_gold Boots.
			#Range: 0.0 ~ 1.0
			bootsChance = 1.0
			#The chance that after each piece of better_gold Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChance = 0.25
			#The chance on hard mode that after each piece of better_gold Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChanceHard = 0.1
			#The chance that if a mob spawns with better_gold Weapons that it will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			weaponEnchantmentChance = 0.25
			#The chance that if a mob spawns with better_gold Armor that they will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			armorEnchantmentChance = 0.5

		#Spawn chances for pieces of plaslitherite gear. Note: These values are after the general mobArmorSpawnRate (or corresponding weapon rate) has been checked, and after an even split between material types has been done.
		[tools.mobArmorSpawnRate.plaslitherite]
			#Whether mobs can spawn with plaslitherite Weapons.
			canSpawnWeapon = true
			#The chance that mobs will spawn with plaslitherite Swords rather than plaslitherite Shovels.
			#Range: 0.0 ~ 1.0
			swordWeight = 0.33
			#The chance that mobs can spawn with plaslitherite Helmets.
			#Range: 0.0 ~ 1.0
			helmetChance = 1.0
			#The chance that mobs can spawn with plaslitherite Chestplates.
			#Range: 0.0 ~ 1.0
			chestplateChance = 1.0
			#The chance that mobs can spawn with plaslitherite Leggings.
			#Range: 0.0 ~ 1.0
			leggingsChance = 1.0
			#The chance that mobs can spawn with plaslitherite Boots.
			#Range: 0.0 ~ 1.0
			bootsChance = 1.0
			#The chance that after each piece of plaslitherite Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChance = 0.25
			#The chance on hard mode that after each piece of plaslitherite Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChanceHard = 0.1
			#The chance that if a mob spawns with plaslitherite Weapons that it will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			weaponEnchantmentChance = 0.25
			#The chance that if a mob spawns with plaslitherite Armor that they will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			armorEnchantmentChance = 0.5

		#Spawn chances for pieces of refined_redstone gear. Note: These values are after the general mobArmorSpawnRate (or corresponding weapon rate) has been checked, and after an even split between material types has been done.
		[tools.mobArmorSpawnRate.refined_redstone]
			#Whether mobs can spawn with refined_redstone Weapons.
			canSpawnWeapon = true
			#The chance that mobs will spawn with refined_redstone Swords rather than refined_redstone Shovels.
			#Range: 0.0 ~ 1.0
			swordWeight = 0.33
			#The chance that mobs can spawn with refined_redstone Helmets.
			#Range: 0.0 ~ 1.0
			helmetChance = 1.0
			#The chance that mobs can spawn with refined_redstone Chestplates.
			#Range: 0.0 ~ 1.0
			chestplateChance = 1.0
			#The chance that mobs can spawn with refined_redstone Leggings.
			#Range: 0.0 ~ 1.0
			leggingsChance = 1.0
			#The chance that mobs can spawn with refined_redstone Boots.
			#Range: 0.0 ~ 1.0
			bootsChance = 1.0
			#The chance that after each piece of refined_redstone Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChance = 0.25
			#The chance on hard mode that after each piece of refined_redstone Armor a mob spawns with that no more pieces will be added. Order of pieces tried is boots, leggings, chestplate, helmet.
			#Range: 0.0 ~ 1.0
			multiplePieceChanceHard = 0.1
			#The chance that if a mob spawns with refined_redstone Weapons that it will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			weaponEnchantmentChance = 0.25
			#The chance that if a mob spawns with refined_redstone Armor that they will be enchanted. This is multiplied modified by the chunk's difficulty modifier.
			#Range: 0.0 ~ 1.0
			armorEnchantmentChance = 0.5

	#Material Settings for Better Gold
	[tools.better_gold]
		#Base attack damage of Better Gold items.
		#Range: 0.0 ~ 3.4028234663852886E38
		better_goldAttackDamage = 2.0
		#Maximum durability of Better Gold shields.
		#Range: > 0
		better_goldShieldDurability = 3360
		#Attack damage modifier of Better Gold swords.
		better_goldSwordDamage = 14.0
		#Attack speed of Better Gold swords.
		better_goldSwordAtkSpeed = -2.4000000953674316
		#Attack damage modifier of Better Gold shovels.
		better_goldShovelDamage = 10.5
		#Attack speed of Better Gold shovels.
		better_goldShovelAtkSpeed = -3.0
		#Attack damage modifier of Better Gold axes.
		better_goldAxeDamage = 16.0
		#Attack speed of Better Gold axes.
		better_goldAxeAtkSpeed = -3.0
		#Attack damage modifier of Better Gold pickaxes.
		better_goldPickaxeDamage = 10.0
		#Attack speed of Better Gold pickaxes.
		better_goldPickaxeAtkSpeed = -2.799999952316284
		#Attack damage modifier of Better Gold hoes.
		better_goldHoeDamage = 0.0
		#Attack speed of Better Gold hoes.
		better_goldHoeAtkSpeed = -1.0
		#Maximum durability of Better Gold tools.
		#Range: > 1
		better_goldToolMaxUses = 8192
		#Efficiency of Better Gold tools.
		better_goldEfficiency = 8.0
		#Attack damage modifier of Better Gold paxels.
		better_goldPaxelDamage = 17.0
		#Attack speed of Better Gold paxels.
		better_goldPaxelAtkSpeed = -2.4000000953674316
		#Efficiency of Better Gold paxels.
		better_goldPaxelEfficiency = 8.0
		#Natural enchantability factor of Better Gold paxels.
		#Range: > 0
		better_goldPaxelEnchantability = 16
		#Maximum durability of Better Gold paxels.
		#Range: > 1
		better_goldPaxelMaxUses = 16384
		#Natural enchantability factor of Better Gold items.
		#Range: > 0
		better_goldEnchantability = 16
		#Base armor toughness value of Better Gold armor.
		#Range: 0.0 ~ 3.4028234663852886E38
		better_goldToughness = 5.0
		#Base armor knockback resistance value of Better Gold armor.
		#Range: 0.0 ~ 3.4028234663852886E38
		better_goldKnockbackResistance = 0.20000000298023224
		#Maximum durability of Better Gold boots.
		#Range: > 1
		better_goldBootDurability = 1650
		#Maximum durability of Better Gold leggings.
		#Range: > 1
		better_goldLeggingDurability = 2250
		#Maximum durability of Better Gold chestplates.
		#Range: > 1
		better_goldChestplateDurability = 2400
		#Maximum durability of Better Gold helmets.
		#Range: > 1
		better_goldHelmetDurability = 1950
		#Protection value of Better Gold boots.
		#Range: > 0
		better_goldBootArmor = 7
		#Protection value of Better Gold leggings.
		#Range: > 0
		better_goldLeggingArmor = 10
		#Protection value of Better Gold chestplates.
		#Range: > 0
		better_goldChestplateArmor = 12
		#Protection value of Better Gold helmets.
		#Range: > 0
		better_goldHelmetArmor = 8

	#Material Settings for Plaslitherite
	[tools.plaslitherite]
		#Base attack damage of Plaslitherite items.
		#Range: 0.0 ~ 3.4028234663852886E38
		plaslitheriteAttackDamage = 2.0
		#Maximum durability of Plaslitherite shields.
		#Range: > 0
		plaslitheriteShieldDurability = 3360
		#Attack damage modifier of Plaslitherite swords.
		plaslitheriteSwordDamage = 16.0
		#Attack speed of Plaslitherite swords.
		plaslitheriteSwordAtkSpeed = -2.4000000953674316
		#Attack damage modifier of Plaslitherite shovels.
		plaslitheriteShovelDamage = 12.5
		#Attack speed of Plaslitherite shovels.
		plaslitheriteShovelAtkSpeed = -3.0
		#Attack damage modifier of Plaslitherite axes.
		plaslitheriteAxeDamage = 18.0
		#Attack speed of Plaslitherite axes.
		plaslitheriteAxeAtkSpeed = -3.0
		#Attack damage modifier of Plaslitherite pickaxes.
		plaslitheritePickaxeDamage = 12.0
		#Attack speed of Plaslitherite pickaxes.
		plaslitheritePickaxeAtkSpeed = -2.799999952316284
		#Attack damage modifier of Plaslitherite hoes.
		plaslitheriteHoeDamage = 2.0
		#Attack speed of Plaslitherite hoes.
		plaslitheriteHoeAtkSpeed = -1.0
		#Maximum durability of Plaslitherite tools.
		#Range: > 1
		plaslitheriteToolMaxUses = 16384
		#Efficiency of Plaslitherite tools.
		plaslitheriteEfficiency = 8.0
		#Attack damage modifier of Plaslitherite paxels.
		plaslitheritePaxelDamage = 19.0
		#Attack speed of Plaslitherite paxels.
		plaslitheritePaxelAtkSpeed = -2.4000000953674316
		#Efficiency of Plaslitherite paxels.
		plaslitheritePaxelEfficiency = 8.0
		#Natural enchantability factor of Plaslitherite paxels.
		#Range: > 0
		plaslitheritePaxelEnchantability = 16
		#Maximum durability of Plaslitherite paxels.
		#Range: > 1
		plaslitheritePaxelMaxUses = 32768
		#Natural enchantability factor of Plaslitherite items.
		#Range: > 0
		plaslitheriteEnchantability = 16
		#Base armor toughness value of Plaslitherite armor.
		#Range: 0.0 ~ 3.4028234663852886E38
		plaslitheriteToughness = 5.0
		#Base armor knockback resistance value of Plaslitherite armor.
		#Range: 0.0 ~ 3.4028234663852886E38
		plaslitheriteKnockbackResistance = 0.25
		#Maximum durability of Plaslitherite boots.
		#Range: > 1
		plaslitheriteBootDurability = 3300
		#Maximum durability of Plaslitherite leggings.
		#Range: > 1
		plaslitheriteLeggingDurability = 4500
		#Maximum durability of Plaslitherite chestplates.
		#Range: > 1
		plaslitheriteChestplateDurability = 4800
		#Maximum durability of Plaslitherite helmets.
		#Range: > 1
		plaslitheriteHelmetDurability = 3900
		#Protection value of Plaslitherite boots.
		#Range: > 0
		plaslitheriteBootArmor = 9
		#Protection value of Plaslitherite leggings.
		#Range: > 0
		plaslitheriteLeggingArmor = 12
		#Protection value of Plaslitherite chestplates.
		#Range: > 0
		plaslitheriteChestplateArmor = 14
		#Protection value of Plaslitherite helmets.
		#Range: > 0
		plaslitheriteHelmetArmor = 10

	#Material Settings for Refined Redstone
	[tools.refined_redstone]
		#Base attack damage of Refined Redstone items.
		#Range: 0.0 ~ 3.4028234663852886E38
		refined_redstoneAttackDamage = 0.0
		#Maximum durability of Refined Redstone shields.
		#Range: > 0
		refined_redstoneShieldDurability = 381
		#Attack damage modifier of Refined Redstone swords.
		refined_redstoneSwordDamage = 7.0
		#Attack speed of Refined Redstone swords.
		refined_redstoneSwordAtkSpeed = -2.4000000953674316
		#Attack damage modifier of Refined Redstone shovels.
		refined_redstoneShovelDamage = 2.5
		#Attack speed of Refined Redstone shovels.
		refined_redstoneShovelAtkSpeed = -3.0
		#Attack damage modifier of Refined Redstone axes.
		refined_redstoneAxeDamage = 9.0
		#Attack speed of Refined Redstone axes.
		refined_redstoneAxeAtkSpeed = -3.0
		#Attack damage modifier of Refined Redstone pickaxes.
		refined_redstonePickaxeDamage = 2.0
		#Attack speed of Refined Redstone pickaxes.
		refined_redstonePickaxeAtkSpeed = -2.799999952316284
		#Attack damage modifier of Refined Redstone hoes.
		refined_redstoneHoeDamage = 0.0
		#Attack speed of Refined Redstone hoes.
		refined_redstoneHoeAtkSpeed = -3.0
		#Maximum durability of Refined Redstone tools.
		#Range: > 1
		refined_redstoneToolMaxUses = 384
		#Efficiency of Refined Redstone tools.
		refined_redstoneEfficiency = 5.0
		#Attack damage modifier of Refined Redstone paxels.
		refined_redstonePaxelDamage = 10.0
		#Attack speed of Refined Redstone paxels.
		refined_redstonePaxelAtkSpeed = -2.4000000953674316
		#Efficiency of Refined Redstone paxels.
		refined_redstonePaxelEfficiency = 5.0
		#Natural enchantability factor of Refined Redstone paxels.
		#Range: > 0
		refined_redstonePaxelEnchantability = 16
		#Maximum durability of Refined Redstone paxels.
		#Range: > 1
		refined_redstonePaxelMaxUses = 768
		#Natural enchantability factor of Refined Redstone items.
		#Range: > 0
		refined_redstoneEnchantability = 16
		#Base armor toughness value of Refined Redstone armor.
		#Range: 0.0 ~ 3.4028234663852886E38
		refined_redstoneToughness = 0.0
		#Base armor knockback resistance value of Refined Redstone armor.
		#Range: 0.0 ~ 3.4028234663852886E38
		refined_redstoneKnockbackResistance = 0.0
		#Maximum durability of Refined Redstone boots.
		#Range: > 1
		refined_redstoneBootDurability = 260
		#Maximum durability of Refined Redstone leggings.
		#Range: > 1
		refined_redstoneLeggingDurability = 300
		#Maximum durability of Refined Redstone chestplates.
		#Range: > 1
		refined_redstoneChestplateDurability = 320
		#Maximum durability of Refined Redstone helmets.
		#Range: > 1
		refined_redstoneHelmetDurability = 220
		#Protection value of Refined Redstone boots.
		#Range: > 0
		refined_redstoneBootArmor = 3
		#Protection value of Refined Redstone leggings.
		#Range: > 0
		refined_redstoneLeggingArmor = 6
		#Protection value of Refined Redstone chestplates.
		#Range: > 0
		refined_redstoneChestplateArmor = 8
		#Protection value of Refined Redstone helmets.
		#Range: > 0
		refined_redstoneHelmetArmor = 3

