StartupEvents.registry('block', event => {
  event.create('mek_inf:flux_dust_block')
    .soundType('stone')
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .textureAll('kubejs:block/flux_dust_block')
  event.create('mek_inf:steel_machine_hull')
    .soundType('metal')
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .textureAll('kubejs:block/steel_machine_hull')
})