
["Mekanism Weaponry Config"]
	#Damage dealt by plasma rifle projectile
	#Range: 0.0 ~ 3.4028234663852886E38
	plasmaRifleDamage = 8.0
	#Cooldown in ticks between when gun can be shot
	#Range: > 0
	plasmaRifleCooldown = 6
	#How much FE should be drained from the guns battery every shot
	#Range: > 0
	plasmaRifleEnergyUsage = 175
	#How many ticks it should take to reload the weapon
	#Range: > 0
	plasmaRifleReloadTime = 45
	#How much heat should accumulate every shot
	#Range: > 0
	plasmaRifleHeatPerShot = 20
	#How much energy the gun can store
	#Range: > 0
	plasmaRifleEnergyCapacity = 50000
	#How fast the gun battery can charge/discharge
	#Range: > 0
	plasmaRifleEnergyTransfer = 1000
	#Damage dealt by railgun rod
	#Range: 0.0 ~ 3.4028234663852886E38
	railgunDamage = 16.0
	#Cooldown in ticks between when gun can be shot
	#Range: > 0
	railgunCooldown = 20
	#How much FE should be drained from the guns battery every shot
	#Range: > 0
	railgunEnergyUsage = 1000
	#How many ticks it should take to reload the weapon
	#Range: > 0
	railgunReloadTime = 55
	#Max ammo the gun can hold
	#Range: > 1
	railgunMaxAmmo = 5
	#How much energy the gun can store
	#Range: > 0
	railgunEnergyCapacity = 75000
	#How fast the gun battery can charge/discharge
	#Range: > 0
	railgunEnergyTransfer = 10000
	#Stats scaling when railgun is in second mode
	#Range: 0.0 ~ 3.4028234663852886E38
	railgunSecondModeScale = 2.0
	#Damage dealt by tesla minigun
	#Range: 0.0 ~ 3.4028234663852886E38
	teslaMinigunDamage = 2.5
	#Cooldown in ticks between when gun can be shot
	#Range: > 0
	teslaMinigunCooldown = 4
	#How much FE should be drained from the guns battery every shot
	#Range: > 0
	teslaMinigunEnergyUsage = 500
	#How many ticks it should take to reload the weapon
	#Range: > 0
	teslaMinigunReloadTime = 100
	#How much heat should accumulate every shot
	#Range: > 0
	teslaMinigunHeatPerShot = 5
	#How much energy the gun can store
	#Range: > 0
	teslaMinigunEnergyCapacity = 75000
	#How fast the gun battery can charge/discharge
	#Range: > 0
	teslaMinigunEnergyTransfer = 10000
	#Damage dealt by gauntlet
	#Range: 0.0 ~ 3.4028234663852886E38
	gauntletDamage = 5.0
	#How much FE should be drained from the battery every shot
	#Range: > 0
	gauntletEnergyUsage = 1000
	#How much energy the gauntlet battery can store
	#Range: > 0
	gauntletEnergyCapacity = 15000
	#How fast the gauntlet battery can charge/discharge
	#Range: > 0
	gauntletEnergyTransfer = 1000

