
#Adjustment of the capacity of the machine's internal tank
[Mekanism_Science]

	[Mekanism_Science.SeawaterPump]
		#Fluid tank capacity (mB). Default: 1000000, Vanilla: 10000
		#Range: > 1
		fluidTankCapacity = 1000000

	[Mekanism_Science.RadiationIrradiatorInput]
		#Chemical tank capacity (mB). Default: 1000000, Vanilla: 10000
		#Range: 1 ~ 9223372036854775807
		inputChemicalTankCapacity = 1000000
		#Chemical tank capacity (mB). Default: 1000000, Vanilla: 10000
		#Range: 1 ~ 9223372036854775807
		outputChemicalTankCapacity = 1000000

	[Mekanism_Science.ChemicalDemolition]
		#Chemical tank capacity (mB). Default: 1000000, Vanilla: 10000
		#Range: 1 ~ 9223372036854775807
		ChemicalTankCapacity = 1000000

	[Mekanism_Science.AirCompressor]
		#Chemical tank capacity (mB). Default: 1000000, Vanilla: 10000
		#Range: 1 ~ 9223372036854775807
		ChemicalTankCapacity = 1000000

	[Mekanism_Science.AdsorptionSeparator]
		#Chemical tank capacity (mB). Default: 1000000, Vanilla: 10000
		#Range: > 1
		inputFluidTankCapacity = 1000000
		#Chemical tank capacity (mB). Default: 1000000, Vanilla: 10000
		#Range: 1 ~ 9223372036854775807
		outputChemicalTankCapacity = 1000000

